// ── PDF Export Service ────────────────────────────────────────────────────────
// Generates a dark-themed, branded itinerary PDF using jsPDF + jspdf-autotable

import type { ItineraryData, TripData, RawItineraryDay } from "@/lib/types/planner.types";

export async function exportItineraryPDF(
  itineraryData: ItineraryData,
  tripData: TripData
): Promise<void> {
  // Dynamic import to keep bundle size lean
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;

  // Brand palette as RGB tuples
  const BRAND: [number, number, number] = [37, 99, 235];
  const CYAN: [number, number, number] = [34, 211, 238];
  const DARK: [number, number, number] = [15, 23, 42];
  const DARK2: [number, number, number] = [20, 30, 50];
  const DARK3: [number, number, number] = [25, 36, 58];
  const WHITE: [number, number, number] = [255, 255, 255];
  const DIM: [number, number, number] = [130, 160, 200];
  const SOFT: [number, number, number] = [180, 200, 230];

  // ── Cover Page ─────────────────────────────────────────────────────────────
  doc.setFillColor(...DARK);
  doc.rect(0, 0, W, 297, "F");

  // Brand accent bar
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, W, 3, "F");

  // Velosta wordmark
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...DIM);
  doc.text("VELOSTA AI  ·  SPATIAL TRAVEL PLAN", W / 2, 18, { align: "center" });

  // Destination title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(...WHITE);
  doc.text(itineraryData.destination || "Your Journey", W / 2, 48, {
    align: "center",
  });

  // Duration subtitle
  if (itineraryData.duration) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(...SOFT);
    doc.text(itineraryData.duration, W / 2, 58, { align: "center" });
  }

  // Meta info box
  const boxY = 72;
  doc.setFillColor(30, 40, 60);
  doc.roundedRect(15, boxY, W - 30, 36, 3, 3, "F");

  const metaItems = [
    ["Budget", tripData.budget ?? itineraryData.totalBudget ?? "—"],
    [
      "Travelers",
      tripData.travelers
        ? `${tripData.travelers.adults} adult${tripData.travelers.adults !== 1 ? "s" : ""}${tripData.travelers.children ? `, ${tripData.travelers.children} child${tripData.travelers.children !== 1 ? "ren" : ""}` : ""}`
        : "—",
    ],
    [
      "Dates",
      tripData.dateRange
        ? `${tripData.dateRange.start} → ${tripData.dateRange.end}`
        : "—",
    ],
    ["Total Est.", itineraryData.totalEstimatedCost ?? "—"],
  ];

  const cellW = (W - 30) / metaItems.length;
  metaItems.forEach(([label, value], i) => {
    const x = 15 + i * cellW + cellW / 2;
    doc.setFontSize(7);
    doc.setTextColor(...DIM);
    doc.setFont("helvetica", "normal");
    doc.text(label.toUpperCase(), x, boxY + 11, { align: "center" });
    doc.setFontSize(10);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    const displayVal = String(value).length > 18 ? String(value).slice(0, 16) + "…" : String(value);
    doc.text(displayVal, x, boxY + 22, { align: "center" });
  });

  // Summary
  if (itineraryData.summary) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(...SOFT);
    const lines = doc.splitTextToSize(itineraryData.summary, W - 30);
    doc.text(lines.slice(0, 5), 15, 120);
  }

  // Budget breakdown
  if (itineraryData.budgetBreakdown) {
    let y = 148;
    doc.setFontSize(10);
    doc.setTextColor(...CYAN);
    doc.setFont("helvetica", "bold");
    doc.text("Budget Breakdown", 15, y);
    y += 7;

    const entries = Object.entries(itineraryData.budgetBreakdown).filter(([, v]) => v);
    entries.forEach(([key, val]) => {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DIM);
      doc.text(key.charAt(0).toUpperCase() + key.slice(1) + ":", 18, y);
      doc.setTextColor(...WHITE);
      doc.text(String(val), 75, y);
      y += 7;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(60, 80, 110);
  doc.text(
    `Generated by Velosta AI · ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`,
    W / 2,
    288,
    { align: "center" }
  );

  // ── Day Pages ──────────────────────────────────────────────────────────────
  const days = itineraryData.itineraryTable ?? [];

  days.forEach((day, dayIdx) => {
    doc.addPage();

    // Dark background
    doc.setFillColor(...DARK);
    doc.rect(0, 0, W, 297, "F");

    // Color-coded day accent stripe
    const DAY_COLORS: [number, number, number][] = [
      [37, 99, 235], [124, 58, 237], [34, 211, 238], [22, 163, 74],
      [245, 158, 11], [234, 88, 12], [220, 38, 38], [8, 145, 178],
    ];
    const dayColor = DAY_COLORS[dayIdx % DAY_COLORS.length];
    doc.setFillColor(...dayColor);
    doc.rect(0, 0, W, 3, "F");

    // Day header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...WHITE);
    const dayTitle = `Day ${day.day}${day.theme ? `  ·  ${day.theme}` : ""}`;
    doc.text(dayTitle, 15, 18);

    if (day.dailyCost) {
      doc.setFontSize(10);
      doc.setTextColor(...dayColor);
      doc.text(day.dailyCost, W - 15, 18, { align: "right" });
    }

    // Activities table
    let nextY = 26;
    if (day.rows && day.rows.length > 0) {
      autoTable(doc, {
        startY: nextY,
        head: [["Time", "Activity", "Description", "Distance", "Cost"]],
        body: day.rows.map((r) => [
          r.time ?? "—",
          r.activity ?? "—",
          r.description ?? "—",
          r.distance ?? "—",
          r.pricing ?? "—",
        ]),
        theme: "grid",
        headStyles: {
          fillColor: dayColor,
          textColor: WHITE,
          fontStyle: "bold",
          fontSize: 7.5,
          cellPadding: 3,
        },
        bodyStyles: {
          fillColor: DARK2,
          textColor: [200, 220, 255] as [number, number, number],
          fontSize: 7.5,
          cellPadding: 3,
        },
        alternateRowStyles: { fillColor: DARK3 },
        columnStyles: {
          0: { cellWidth: 20, fontStyle: "bold" },
          1: { cellWidth: 38, fontStyle: "bold" },
          2: { cellWidth: 75 },
          3: { cellWidth: 22, textColor: DIM },
          4: { cellWidth: 22, textColor: CYAN, fontStyle: "bold" },
        },
        margin: { left: 10, right: 10 },
      });

      nextY = ((doc as any).lastAutoTable?.finalY ?? 60) + 6;
    }

    // Meals
    if (day.meals) {
      const mealEntries = [
        day.meals.breakfast && `Breakfast: ${day.meals.breakfast}`,
        day.meals.lunch && `Lunch: ${day.meals.lunch}`,
        day.meals.dinner && `Dinner: ${day.meals.dinner}`,
      ].filter(Boolean) as string[];

      if (mealEntries.length > 0) {
        doc.setFontSize(8.5);
        doc.setTextColor(...CYAN);
        doc.setFont("helvetica", "bold");
        doc.text("Meals", 15, nextY);
        nextY += 5;

        mealEntries.forEach((m) => {
          doc.setFontSize(8);
          doc.setTextColor(...SOFT);
          doc.setFont("helvetica", "normal");
          doc.text(m, 18, nextY);
          nextY += 5.5;
        });

        nextY += 2;
      }
    }

    // Accommodation
    if (day.accommodation) {
      doc.setFontSize(8.5);
      doc.setTextColor(...CYAN);
      doc.setFont("helvetica", "bold");
      doc.text("Stay", 15, nextY);
      doc.setFontSize(8);
      doc.setTextColor(...SOFT);
      doc.setFont("helvetica", "normal");
      doc.text(day.accommodation, 30, nextY);
    }

    // Page footer
    doc.setFontSize(7);
    doc.setTextColor(50, 70, 100);
    doc.text(`Velosta AI · Day ${day.day} of ${days.length}`, W / 2, 290, {
      align: "center",
    });
  });

  // ── Final summary page ─────────────────────────────────────────────────────
  if (itineraryData.expenseSummary || itineraryData.localTips?.length) {
    doc.addPage();
    doc.setFillColor(...DARK);
    doc.rect(0, 0, W, 297, "F");
    doc.setFillColor(...BRAND);
    doc.rect(0, 0, W, 3, "F");

    let y = 18;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...WHITE);
    doc.text("Trip Summary", 15, y);
    y += 10;

    const es = itineraryData.expenseSummary;
    if (es) {
      if (es.totalPerPerson) {
        doc.setFontSize(9);
        doc.setTextColor(...DIM);
        doc.setFont("helvetica", "normal");
        doc.text("Total Per Person", 15, y);
        doc.setFontSize(12);
        doc.setTextColor(...CYAN);
        doc.setFont("helvetica", "bold");
        doc.text(es.totalPerPerson, 70, y);
        y += 8;
      }
      if (es.totalForGroup) {
        doc.setFontSize(9);
        doc.setTextColor(...DIM);
        doc.setFont("helvetica", "normal");
        doc.text("Total for Group", 15, y);
        doc.setFontSize(12);
        doc.setTextColor(...WHITE);
        doc.setFont("helvetica", "bold");
        doc.text(es.totalForGroup, 70, y);
        y += 12;
      }

      if (es.costSavingTips?.length) {
        doc.setFontSize(10);
        doc.setTextColor([22, 163, 74] as unknown as string);
        doc.setFont("helvetica", "bold");
        doc.text("Cost Saving Tips", 15, y);
        y += 6;

        es.costSavingTips.forEach((tip) => {
          doc.setFontSize(8.5);
          doc.setTextColor(...SOFT);
          doc.setFont("helvetica", "normal");
          const lines = doc.splitTextToSize(`• ${tip}`, W - 30);
          doc.text(lines, 18, y);
          y += lines.length * 5.5;
        });
        y += 4;
      }
    }

    if (itineraryData.localTips?.length) {
      doc.setFontSize(10);
      doc.setTextColor(245, 158, 11);
      doc.setFont("helvetica", "bold");
      doc.text("Local Tips", 15, y);
      y += 6;

      itineraryData.localTips.forEach((tip) => {
        doc.setFontSize(8.5);
        doc.setTextColor(...SOFT);
        doc.setFont("helvetica", "normal");
        const lines = doc.splitTextToSize(`• ${tip}`, W - 30);
        doc.text(lines, 18, y);
        y += lines.length * 5.5;
      });
    }
  }

  const filename =
    `${(itineraryData.destination ?? "velosta").replace(/[^a-z0-9]/gi, "-").toLowerCase()}-itinerary.pdf`;

  doc.save(filename);
}


