// ── Destination Pins Data ──────────────────────────────────────────────────────
// Static dataset of popular Indian destinations for budget-based map exploration

export interface DestinationPin {
  id: string;
  name: string;
  state: string;
  coordinates: [number, number]; // [lng, lat]
  budgetTier: "budget" | "mid" | "premium" | "weekend";
  estimatedCost: string;
  idealDays: string;
  highlights: string[];
  season: string;
  tagline: string;
}

export const DESTINATION_PINS: DestinationPin[] = [
  // Budget tier (₹3k–5k)
  {
    id: "pondicherry",
    name: "Pondicherry",
    state: "Tamil Nadu",
    coordinates: [79.8083, 11.9416],
    budgetTier: "budget",
    estimatedCost: "₹3,500",
    idealDays: "2–3 days",
    highlights: ["French Quarter", "Auroville", "Paradise Beach"],
    season: "Oct–Mar",
    tagline: "A French coastal charm",
  },
  {
    id: "hampi",
    name: "Hampi",
    state: "Karnataka",
    coordinates: [76.4600, 15.3350],
    budgetTier: "budget",
    estimatedCost: "₹3,000",
    idealDays: "2–3 days",
    highlights: ["Virupaksha Temple", "Stone Chariot", "Hippie Island"],
    season: "Oct–Feb",
    tagline: "Ancient ruins, modern vibes",
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    coordinates: [78.2676, 30.0869],
    budgetTier: "budget",
    estimatedCost: "₹4,000",
    idealDays: "3 days",
    highlights: ["River Rafting", "Laxman Jhula", "Beatles Ashram"],
    season: "Sep–Jun",
    tagline: "Yoga capital meets adventure",
  },
  {
    id: "pushkar",
    name: "Pushkar",
    state: "Rajasthan",
    coordinates: [74.5512, 26.4897],
    budgetTier: "budget",
    estimatedCost: "₹3,500",
    idealDays: "2 days",
    highlights: ["Pushkar Lake", "Brahma Temple", "Desert Camping"],
    season: "Oct–Mar",
    tagline: "Sacred desert lakeside magic",
  },
  {
    id: "mcleodganj",
    name: "McLeodGanj",
    state: "Himachal Pradesh",
    coordinates: [76.3234, 32.2432],
    budgetTier: "budget",
    estimatedCost: "₹4,500",
    idealDays: "3 days",
    highlights: ["Triund Trek", "Dalai Lama Temple", "Bhagsu Waterfall"],
    season: "Mar–Jun, Sep–Nov",
    tagline: "Himalayan peace & trails",
  },
  {
    id: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    coordinates: [82.9913, 25.3176],
    budgetTier: "budget",
    estimatedCost: "₹3,500",
    idealDays: "2–3 days",
    highlights: ["Ganga Aarti", "Kashi Vishwanath", "Boat Ride"],
    season: "Oct–Mar",
    tagline: "Oldest living city on Earth",
  },
  {
    id: "varkala",
    name: "Varkala",
    state: "Kerala",
    coordinates: [76.7169, 8.7379],
    budgetTier: "budget",
    estimatedCost: "₹4,000",
    idealDays: "2–3 days",
    highlights: ["Cliff Beach", "Papanasam Beach", "Janardhana Temple"],
    season: "Oct–Feb",
    tagline: "Kerala's hidden cliff beach",
  },

  // Mid tier (₹5k–8k)
  {
    id: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    coordinates: [73.6833, 24.5854],
    budgetTier: "mid",
    estimatedCost: "₹6,500",
    idealDays: "3–4 days",
    highlights: ["City Palace", "Lake Pichola", "Jagdish Temple"],
    season: "Oct–Mar",
    tagline: "City of lakes and palaces",
  },
  {
    id: "goa",
    name: "Goa",
    state: "Goa",
    coordinates: [73.8567, 15.2993],
    budgetTier: "mid",
    estimatedCost: "₹7,000",
    idealDays: "4 days",
    highlights: ["Beaches", "Dudhsagar Falls", "Old Goa Churches"],
    season: "Nov–Feb",
    tagline: "Beaches, vibes, and sunsets",
  },
  {
    id: "kodaikanal",
    name: "Kodaikanal",
    state: "Tamil Nadu",
    coordinates: [77.4893, 10.2381],
    budgetTier: "mid",
    estimatedCost: "₹5,500",
    idealDays: "3 days",
    highlights: ["Kodai Lake", "Pillar Rocks", "Coaker's Walk"],
    season: "Oct–Jun",
    tagline: "Princess of hill stations",
  },
  {
    id: "coorg",
    name: "Coorg",
    state: "Karnataka",
    coordinates: [75.7382, 12.4244],
    budgetTier: "mid",
    estimatedCost: "₹6,000",
    idealDays: "3 days",
    highlights: ["Abbey Falls", "Raja's Seat", "Coffee Plantations"],
    season: "Oct–Mar",
    tagline: "Scotland of India, coffee land",
  },
  {
    id: "ooty",
    name: "Ooty",
    state: "Tamil Nadu",
    coordinates: [76.6950, 11.4102],
    budgetTier: "mid",
    estimatedCost: "₹6,000",
    idealDays: "3 days",
    highlights: ["Toy Train", "Botanical Gardens", "Doddabetta Peak"],
    season: "Oct–Jun",
    tagline: "Queen of hill stations",
  },
  {
    id: "jaisalmer",
    name: "Jaisalmer",
    state: "Rajasthan",
    coordinates: [70.9083, 26.9157],
    budgetTier: "mid",
    estimatedCost: "₹7,500",
    idealDays: "3–4 days",
    highlights: ["Golden Fort", "Sam Dunes", "Gadisar Lake"],
    season: "Oct–Mar",
    tagline: "Golden city in the Thar",
  },
  {
    id: "alleppey",
    name: "Alleppey",
    state: "Kerala",
    coordinates: [76.3388, 9.4981],
    budgetTier: "mid",
    estimatedCost: "₹7,000",
    idealDays: "2–3 days",
    highlights: ["Houseboats", "Backwaters", "Marari Beach"],
    season: "Sep–Mar",
    tagline: "Venice of the East",
  },

  // Premium tier (₹8k–15k)
  {
    id: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    coordinates: [77.1734, 32.2396],
    budgetTier: "premium",
    estimatedCost: "₹10,000",
    idealDays: "5 days",
    highlights: ["Rohtang Pass", "Solang Valley", "Old Manali"],
    season: "Oct–Jun",
    tagline: "Mountain gateway adventure",
  },
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    coordinates: [75.7873, 26.9124],
    budgetTier: "premium",
    estimatedCost: "₹9,000",
    idealDays: "4 days",
    highlights: ["Amber Fort", "Hawa Mahal", "City Palace"],
    season: "Oct–Mar",
    tagline: "The Pink City of royalty",
  },
  {
    id: "munnar",
    name: "Munnar",
    state: "Kerala",
    coordinates: [77.0595, 10.0889],
    budgetTier: "premium",
    estimatedCost: "₹8,500",
    idealDays: "4 days",
    highlights: ["Tea Gardens", "Eravikulam", "Mattupetty Dam"],
    season: "Sep–May",
    tagline: "Tea hills in the Western Ghats",
  },
  {
    id: "ladakh",
    name: "Leh-Ladakh",
    state: "Ladakh",
    coordinates: [77.5770, 34.1526],
    budgetTier: "premium",
    estimatedCost: "₹14,000",
    idealDays: "6–7 days",
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La"],
    season: "Jun–Sep",
    tagline: "Land of high passes",
  },
  {
    id: "andaman",
    name: "Andaman Islands",
    state: "Andaman & Nicobar",
    coordinates: [92.7265, 11.7401],
    budgetTier: "premium",
    estimatedCost: "₹15,000",
    idealDays: "5–6 days",
    highlights: ["Havelock", "Radhanagar Beach", "Scuba Diving"],
    season: "Oct–May",
    tagline: "Tropical paradise archipelago",
  },
  {
    id: "shimla",
    name: "Shimla",
    state: "Himachal Pradesh",
    coordinates: [77.1734, 31.1048],
    budgetTier: "premium",
    estimatedCost: "₹9,000",
    idealDays: "4 days",
    highlights: ["Mall Road", "Jakhoo Temple", "Kufri"],
    season: "Mar–Jun, Oct–Feb",
    tagline: "Queen of the Hills",
  },

  // Weekend escapes (Under ₹4k)
  {
    id: "lonavala",
    name: "Lonavala",
    state: "Maharashtra",
    coordinates: [73.4073, 18.7546],
    budgetTier: "weekend",
    estimatedCost: "₹2,500",
    idealDays: "1–2 days",
    highlights: ["Tiger Point", "Bhushi Dam", "Karla Caves"],
    season: "Jun–Mar",
    tagline: "Mumbai's quick hill escape",
  },
  {
    id: "nandihills",
    name: "Nandi Hills",
    state: "Karnataka",
    coordinates: [77.6835, 13.3702],
    budgetTier: "weekend",
    estimatedCost: "₹1,500",
    idealDays: "1 day",
    highlights: ["Sunrise Point", "Tipu's Drop", "Cycling"],
    season: "Sep–Feb",
    tagline: "Bangalore's sunrise spot",
  },
  {
    id: "alibaug",
    name: "Alibaug",
    state: "Maharashtra",
    coordinates: [72.8777, 18.6414],
    budgetTier: "weekend",
    estimatedCost: "₹3,000",
    idealDays: "2 days",
    highlights: ["Alibaug Beach", "Kolaba Fort", "Water Sports"],
    season: "Oct–May",
    tagline: "Maharashtra's coastal charm",
  },
  {
    id: "mahabaleshwar",
    name: "Mahabaleshwar",
    state: "Maharashtra",
    coordinates: [73.6477, 17.9237],
    budgetTier: "weekend",
    estimatedCost: "₹3,500",
    idealDays: "2 days",
    highlights: ["Arthur's Seat", "Venna Lake", "Strawberry Farms"],
    season: "Oct–Jun",
    tagline: "Strawberry hills, misty views",
  },
  {
    id: "pondicherry-we",
    name: "Pondicherry",
    state: "Tamil Nadu",
    coordinates: [79.8083, 11.9416],
    budgetTier: "weekend",
    estimatedCost: "₹3,500",
    idealDays: "2 days",
    highlights: ["White Town", "Rock Beach", "Promenade"],
    season: "Oct–Mar",
    tagline: "Quick French Quarter getaway",
  },
  {
    id: "coorg-we",
    name: "Coorg",
    state: "Karnataka",
    coordinates: [75.7382, 12.4244],
    budgetTier: "weekend",
    estimatedCost: "₹3,500",
    idealDays: "2 days",
    highlights: ["Abbey Falls", "Coffee Estate Stay", "Namdroling Monastery"],
    season: "Oct–Mar",
    tagline: "Coffee and mist quick escape",
  },
];

/** Filter destinations by budget tier ID */
export function getDestinationsByTier(tierId: string): DestinationPin[] {
  return DESTINATION_PINS.filter((d) => d.budgetTier === tierId);
}

/** Get pin color based on budget tier */
export function getPinColor(tierId: string): string {
  switch (tierId) {
    case "budget":   return "#D97706"; // amber
    case "mid":      return "#EA580C"; // orange
    case "premium":  return "#92400E"; // deep amber
    case "weekend":  return "#F59E0B"; // yellow amber
    default:         return "#D97706";
  }
}

