import type { CityHub, DemoBike } from "./types";

export const BIKE_IMAGES = {
  classic350: "/images/bikes/classic350.webp",
  activa6g: "/images/bikes/activa-6g.png",
} as const;

export const CITY_HUBS: CityHub[] = [
  { id: "hyderabad", name: "Hyderabad", state: "Telangana", lat: 17.385, lng: 78.4867 },
  { id: "bangalore", name: "Bangalore", state: "Karnataka", lat: 12.9716, lng: 77.5946 },
  { id: "goa", name: "Goa", state: "Goa", lat: 15.2993, lng: 74.124 },
  { id: "delhi", name: "Delhi", state: "Delhi", lat: 28.6139, lng: 77.209 },
  { id: "mumbai", name: "Mumbai", state: "Maharashtra", lat: 19.076, lng: 72.8777 },
  { id: "jaipur", name: "Jaipur", state: "Rajasthan", lat: 26.9124, lng: 75.7873 },
  { id: "manali", name: "Manali", state: "Himachal Pradesh", lat: 32.2396, lng: 77.1887 },
  { id: "pune", name: "Pune", state: "Maharashtra", lat: 18.5204, lng: 73.8567 },
];

export const DEMO_BIKES: DemoBike[] = [
  {
    id: "re-classic-hyd",
    name: "Classic 350",
    brand: "Royal Enfield",
    category: "premium",
    cityId: "hyderabad",
    hubName: "Jubilee Hills Hub",
    lat: 17.4326,
    lng: 78.4071,
    pricePerDay: 899,
    deposit: 3000,
    rating: 4.9,
    reviewCount: 312,
    engine: "349 cc",
    mileage: "35 km/l",
    transmission: "Manual",
    image: BIKE_IMAGES.classic350,
    tags: ["Helmet included", "Highway ready"],
    available: 4,
  },
  {
    id: "activa-hyd",
    name: "Activa 6G",
    brand: "Honda",
    category: "scooter",
    cityId: "hyderabad",
    hubName: "Gachibowli Station",
    lat: 17.4401,
    lng: 78.3489,
    pricePerDay: 399,
    deposit: 1500,
    rating: 4.7,
    reviewCount: 528,
    engine: "109 cc",
    mileage: "45 km/l",
    transmission: "Automatic",
    image: BIKE_IMAGES.activa6g,
    tags: ["Best for city", "Helmet included"],
    available: 12,
  },
  {
    id: "apache-blr",
    name: "Apache RTR 160",
    brand: "TVS",
    category: "sport",
    cityId: "bangalore",
    hubName: "Indiranagar Pickup",
    lat: 12.9784,
    lng: 77.6408,
    pricePerDay: 649,
    deposit: 2000,
    rating: 4.8,
    reviewCount: 201,
    engine: "159 cc",
    mileage: "40 km/l",
    transmission: "Manual",
    image: "https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80",
    tags: ["Sport tuned", "ABS"],
    available: 6,
  },
  {
    id: "ather-blr",
    name: "450X",
    brand: "Ather",
    category: "electric",
    cityId: "bangalore",
    hubName: "Koramangala EV Bay",
    lat: 12.9352,
    lng: 77.6245,
    pricePerDay: 549,
    deposit: 2500,
    rating: 4.6,
    reviewCount: 89,
    engine: "Electric",
    mileage: "146 km range",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1598550476439-68477869f668?w=800&q=80",
    tags: ["Zero emissions", "Fast charge"],
    available: 3,
  },
  {
    id: "duke-goa",
    name: "Duke 200",
    brand: "KTM",
    category: "sport",
    cityId: "goa",
    hubName: "Calangute Beach Hub",
    lat: 15.5439,
    lng: 73.7553,
    pricePerDay: 799,
    deposit: 3500,
    rating: 4.9,
    reviewCount: 167,
    engine: "199 cc",
    mileage: "30 km/l",
    transmission: "Manual",
    image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&q=80",
    tags: ["Coastal rides", "Premium"],
    available: 2,
  },
  {
    id: "jupiter-goa",
    name: "Jupiter 125",
    brand: "TVS",
    category: "scooter",
    cityId: "goa",
    hubName: "Panaji Central",
    lat: 15.4909,
    lng: 73.8278,
    pricePerDay: 349,
    deposit: 1200,
    rating: 4.5,
    reviewCount: 445,
    engine: "124 cc",
    mileage: "50 km/l",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1622185130655-53705906558e?w=800&q=80",
    tags: ["Budget friendly", "Helmet included"],
    available: 15,
  },
  {
    id: "himalayan-del",
    name: "Himalayan 450",
    brand: "Royal Enfield",
    category: "premium",
    cityId: "delhi",
    hubName: "Connaught Place",
    lat: 28.6315,
    lng: 77.2167,
    pricePerDay: 1199,
    deposit: 5000,
    rating: 4.8,
    reviewCount: 94,
    engine: "452 cc",
    mileage: "28 km/l",
    transmission: "Manual",
    image: BIKE_IMAGES.classic350,
    tags: ["Adventure", "Outstation OK"],
    available: 2,
  },
  {
    id: "splendor-del",
    name: "Splendor Plus",
    brand: "Hero",
    category: "commuter",
    cityId: "delhi",
    hubName: "Karol Bagh Hub",
    lat: 28.6519,
    lng: 77.1909,
    pricePerDay: 299,
    deposit: 1000,
    rating: 4.4,
    reviewCount: 892,
    engine: "97 cc",
    mileage: "60 km/l",
    transmission: "Manual",
    image: "https://images.unsplash.com/photo-1605557626850-3e6e0a6b2a2e?w=800&q=80",
    tags: ["Daily commute", "Fuel efficient"],
    available: 20,
  },
  {
    id: "re-mum",
    name: "Meteor 350",
    brand: "Royal Enfield",
    category: "premium",
    cityId: "mumbai",
    hubName: "Bandra West",
    lat: 19.0596,
    lng: 72.8295,
    pricePerDay: 949,
    deposit: 3500,
    rating: 4.7,
    reviewCount: 156,
    engine: "349 cc",
    mileage: "32 km/l",
    transmission: "Manual",
    image: BIKE_IMAGES.classic350,
    tags: ["Cruise comfort", "Helmet included"],
    available: 5,
  },
  {
    id: "ntorq-mum",
    name: "Ntorq 125",
    brand: "TVS",
    category: "scooter",
    cityId: "mumbai",
    hubName: "Andheri East",
    lat: 19.1136,
    lng: 72.8697,
    pricePerDay: 449,
    deposit: 1500,
    rating: 4.6,
    reviewCount: 334,
    engine: "124 cc",
    mileage: "42 km/l",
    transmission: "Automatic",
    image: BIKE_IMAGES.activa6g,
    tags: ["Smart connect", "City rides"],
    available: 8,
  },
  {
    id: "cb350-jai",
    name: "CB350 H'ness",
    brand: "Honda",
    category: "premium",
    cityId: "jaipur",
    hubName: "MI Road Hub",
    lat: 26.9124,
    lng: 75.7873,
    pricePerDay: 849,
    deposit: 3000,
    rating: 4.8,
    reviewCount: 78,
    engine: "348 cc",
    mileage: "35 km/l",
    transmission: "Manual",
    image: "https://images.unsplash.com/photo-1619451330602-1b6061a3e2d5?w=800&q=80",
    tags: ["Heritage rides", "Premium"],
    available: 3,
  },
  {
    id: "activa-manali",
    name: "Activa 6G",
    brand: "Honda",
    category: "scooter",
    cityId: "manali",
    hubName: "Mall Road Pickup",
    lat: 32.2432,
    lng: 77.1892,
    pricePerDay: 499,
    deposit: 2000,
    rating: 4.7,
    reviewCount: 112,
    engine: "109 cc",
    mileage: "40 km/l",
    transmission: "Automatic",
    image: BIKE_IMAGES.activa6g,
    tags: ["Mountain routes", "Helmet included"],
    available: 7,
  },
];

export const POPULAR_CITIES = ["Hyderabad", "Bangalore", "Goa", "Delhi", "Mumbai", "Jaipur", "Pune", "Manali"];

export const CITY_SHOWCASE = [
  { id: "bangalore", name: "Bangalore", image: "/images/trending/city-tours.jpg", bikeCount: 48, startingPrice: 349 },
  { id: "hyderabad", name: "Hyderabad", image: "/images/chakrata.webp", bikeCount: 52, startingPrice: 399 },
  { id: "delhi", name: "Delhi", image: "/images/trending/museum.jpg", bikeCount: 61, startingPrice: 299 },
  { id: "mumbai", name: "Mumbai", image: "/images/trending/beach-tours.jpg", bikeCount: 44, startingPrice: 449 },
  { id: "goa", name: "Goa", image: "/images/desert-atv.jpg", bikeCount: 38, startingPrice: 349 },
  { id: "jaipur", name: "Jaipur", image: "/images/trending/food.jpg", bikeCount: 29, startingPrice: 399 },
  { id: "pune", name: "Pune", image: "/images/trending/hiking.jpg", bikeCount: 35, startingPrice: 379 },
  { id: "manali", name: "Manali", image: "/images/mcleodganj.jpg", bikeCount: 22, startingPrice: 499 },
];

export const WHY_VELOSTA = [
  { title: "Verified Fleet", desc: "100% inspected vehicles with documented service history before every handover." },
  { title: "Zero Hidden Charges", desc: "Transparent pricing — what you see at booking is what you pay at pickup." },
  { title: "Flexible Rentals", desc: "Daily, weekly, and monthly plans with easy extensions from the app." },
  { title: "Roadside Assistance", desc: "24/7 pan-India support line with average 28-minute response time." },
  { title: "Insurance Included", desc: "Comprehensive third-party coverage bundled with every rental." },
  { title: "24/7 Customer Support", desc: "Live chat, phone, and WhatsApp support around the clock." },
];

export const RENTAL_PACKAGES = [
  { id: "daily", name: "Daily Rental", price: "From ₹299/day", benefits: ["Best for city rides", "Helmet included", "Instant confirmation"], cta: "Book daily" },
  { id: "weekend", name: "Weekend Escape", price: "From ₹799/weekend", benefits: ["Fri–Sun pricing", "Free km bundle", "Priority pickup"], cta: "Plan weekend" },
  { id: "weekly", name: "Weekly Adventure", price: "From ₹2,499/week", benefits: ["7-day discount", "2 free extensions", "Premium models"], cta: "Go weekly" },
  { id: "monthly", name: "Monthly Subscription", price: "From ₹4,793/month", benefits: ["Lowest per-day rate", "Home delivery", "Maintenance included"], cta: "Subscribe" },
  { id: "corporate", name: "Corporate Rentals", price: "Custom pricing", benefits: ["Fleet accounts", "GST invoicing", "Dedicated manager"], cta: "Contact sales" },
];

export const TESTIMONIALS = [
  { name: "Arjun Mehta", city: "Bangalore", rating: 5, review: "Booked a Classic 350 for a Coorg trip. Pickup was seamless, bike was spotless. Best rental experience in India.", avatar: "AM" },
  { name: "Priya Sharma", city: "Hyderabad", rating: 5, review: "Used Velosta for daily commute for 3 weeks. Transparent pricing, low deposit, and excellent support when I needed a extension.", avatar: "PS" },
  { name: "Rahul Desai", city: "Goa", rating: 5, review: "Rented an Activa for beach hopping. Quick booking, fair fuel policy, and the helmet quality was surprisingly good.", avatar: "RD" },
  { name: "Kavya Reddy", city: "Mumbai", rating: 4, review: "Corporate team uses Velosta for client visits. Reliable fleet, easy invoicing, and always on time for delivery.", avatar: "KR" },
];

export const PLATFORM_STATS = [
  { value: 50000, suffix: "+", label: "Successful Bookings" },
  { value: 100, suffix: "+", label: "Vehicle Models" },
  { value: 50, suffix: "+", label: "Locations" },
  { value: 4.8, suffix: "★", label: "Average Rating", decimals: 1 },
];

export const FAQ_ITEMS = [
  { q: "What documents are required?", a: "Valid driving licence, government ID (Aadhaar/passport), and booking confirmation at pickup." },
  { q: "How does the security deposit work?", a: "Collected at booking and refunded within 5–7 business days after undamaged return." },
  { q: "Is fuel included?", a: "No. Pick up and return with the same fuel level. You pay for fuel used during the trip." },
  { q: "What is the cancellation policy?", a: "Free cancellation up to 24 hours before pickup. Later cancellations may incur a small fee." },
  { q: "Can I extend my rental?", a: "Yes — extend via app or support before drop-off time, subject to availability." },
  { q: "Is insurance included?", a: "Third-party insurance is included. Optional comprehensive cover available at checkout." },
];

export const HERO_LIFESTYLE_IMAGE =
  "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=1400&q=85&auto=format&fit=crop";

export const TOP_SELLING_IDS = ["re-classic-hyd", "activa-hyd", "apache-blr", "duke-goa", "ather-blr", "himalayan-del", "re-mum", "cb350-jai"];
